name: CI/CD Pipeline for Retro-Sphere

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # 1. SonarCloud Analysis Job
  sonarcloud-analysis:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=amankrs21_Retro-Sphere
            -Dsonar.organization=amankrs21
          projectBaseDir: .


  # 2. Express App Hosting Job (depends on SonarCloud success, but only runs on push to `main`)
  express-build:
    name: Express Build
    runs-on: ubuntu-latest
    needs: sonarcloud-analysis
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies for Express app
        run: npm install
        working-directory: ./server

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip


  # 3. Deploy to Azure Web App (depends on Express app deployment success)
  express-deployment:
    name: Express Deployment
    runs-on: ubuntu-latest
    needs: express-build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_88302B60E93C4747819AA9F0288F9A14 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_87FC4A83EDA9432CBA37E5B5840E928C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_344BA2337F1A42808592A2E7E507F118 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'retro-sphere'
          slot-name: 'Production'
          package: ./server


  # 4. React App Hosting to Cloudflare (depends on Azure Web App deployment success)
  ui-deployment:
    name: UI Deployment
    runs-on: ubuntu-latest
    needs: express-deployment
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies for React app
        run: npm install
        working-directory: ./client

      - name: Build React app
        run: |
          echo "VITE_WS_URL=${{ secrets.VITE_WS_URL }}" >> .env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
          echo "VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}" >> .env
          npm run build
        working-directory: ./client

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'retro-sphere'
          directory: 'client/dist'
